### ISSUE TITLE
A couple of suggestions

### ISSUE THREAD

**Issue by lh3** [mourisl/Lighter#13]
1. Write messages to stderr instead of stdout. The key difference is that data written to stdout is only sent to a redirected file when some buffer is full, but data written to stderr immediately update the redirected file. When I submit a lighter job to LSF/SGE/etc, I do not see the progress until it finishes. Writing messages to stderr won't have this problem.

2. Lighter is slow when it is linked against zlib-1.2.3. Here is part of the timing report when lighter is statically linked against zlib-1.2.8 (4 seconds to read through the input file):
  ```
  [2015-01-10 19:17:32] Scanning the input files to infer alpha(sampling rate)
  [2015-01-10 19:17:36] Average coverage is 43.913 and alpha is 0.159
  ```
  And here is when zlib-1.2.3 is in use (31 seconds):
  ```
  [2015-01-10 19:17:49] Scanning the input files to infer alpha(sampling rate)
  [2015-01-10 19:18:20] Average coverage is 43.913 and alpha is 0.159
  ```
  The huge performance difference is probably caused by the use of `gzgets()`. In zlib-1.2.3, this function is not buffered and performs badly. Zlib-1.2.4 or later uses an internal buffer which dramatically improves the performance. Please see [this blog post](https://attractivechaos.wordpress.com/2010/05/20/what-does-zlib-1-2-5-bring-to-us/) for details. Note that vcftools also has this issue. It warns the user when an old zlib is on the system. You may do the same. I am also [providing a precompiled binary](https://sourceforge.net/projects/biobin/files/error_correction/) with zlib-1.2.8 statically linked.

  BTW, sga @jts is using a [3rd-party C++ wrapper](https://github.com/jts/sga/tree/master/src/Thirdparty) for zlib. I guess it should be performant with zlib-1.2.3. You may also consider to use that. Two additional files only.

**Comment by mourisl** [comment]
Thank you for the suggestions!
I have changed the output of messages to stderr. Lighter also checks the zlib version if the input file is gzip'ed now and output a warning if the version is lower than 1.2.4.
