### ISSUE TITLE
Update quality scores when doing error correction

### ISSUE THREAD

**Issue by chuckcoder** [mourisl/Lighter#15]
Would it be possible to update the quality scores of corrected bases? Not sure if there is a clever way to do it based on confidence of the trusted kmer but even setting them to a constant user specified value would be nice so that downstream applications don't ignore those bases.

**Comment by mourisl** [comment]
I just added a new option "-newQual" that set a new constant quality score for the bases that are corrected.

**Comment by chuckcoder** [comment]
Thanks! Just tried it and looks good. Really appreciate the amazingly fast turn around time!
