### ISSUE TITLE
modify extension of output files

### ISSUE THREAD

**Issue by cprybol** [mourisl/Lighter#16]
running Lighter with paired end read files ending in the extension `.R1.fastq.gz` and `.R2.fastq.gz` yields output files with the extensions `.R1.fastq.cor.fq.gz` and `.R2.fastq.cor.fq.gz`.

could you drop the redundant `.fastq` extension when naming the output file?

my running command is 
`lighter -r "$f" -r "$reverse" -K 19 41020000 -od "$OUT_DIR" -trim -stable -t 8 2>> "$OUT_DIR/lighter.out"`

**Comment by mourisl** [comment]
Good point. The redundant "fastq" does not look well on the output file. I've removed that and uploaded a new version. Thanks.

**Comment by cprybol** [comment]
Just tried out updated version and the output looks great, thanks for revising the code so quickly!
