### ISSUE TITLE
selecting k-mer size greater than 32

### ISSUE THREAD

**Issue by AisaacO** [mourisl/Lighter#18]
I am trying to use k-mer size greater than the 32 specified by lighter as the maximum and have not been able to do that. Is there a way to increase the maximum k-mer length of lighter from 32 to a higher value?

**Comment by mourisl** [comment]
In Lighter, the data structure uses 64bit to represent a kmer, so the maximum kmer length is 32 (each nucleotide is represented by 2 bit). As a result, in current version, Lighter does not allow the kmer length greater than 32.

**Comment by AisaacO** [comment]
okay I thought I could rebuild and adjust it by specifying a higher kmer
value in the main.cpp
Thanks anyways

On Tue, Oct 20, 2015 at 11:54 AM, Li Song <notifications@github.com> wrote:

> In Lighter, the data structure uses 64bit to represent a kmer, so the
> maximum kmer length is 32 (each nucleotide is represented by 2 bit). As a
> result, in current version, Lighter does not allow the kmer length greater
> than 32.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mourisl/Lighter/issues/18#issuecomment-149631526>.
>



-- 
*Isaac Akogwu*
Graduate Research Assistant
Data Mining and Bioinformatics Lab
President, Graduate Student Association
Department of Computational Science
Representative, Graduate Student Senate
The University of Southern Mississippi
Hattiesburg, MS.

**Comment by mourisl** [comment]
Sorry for the late reply. You can now set higher kmer value in the utils.h file and the rebuild Lighter to use longer kmers.
