### ISSUE TITLE
Invalid fastq files produced

### ISSUE THREAD

**Issue by habibr** [mourisl/Lighter#19]
Hi,
I used lighter recently and found out that sometimes it produced invalid fastq files like this:

@ST-E00114:418:HHKV7CCXX:8:1109:26484:40020 2:N:0:GCCAAT
TTCAAGAGGTCTTAAGGAGGCTAACTCATATATAGGTTAGGTCTAGATCTAGAGGATGAGAGCATGGGAGACATGGATGTACATAGACTCGATAAGTACTT
+
AA<F<FAFAA<,FFKKK<FFFKKKKKKKKKKKFKKKAFFF79:40020 2:N:0:GCCAAT

As shown, the quality line is truncated and merged with a segment of the header line.

**Comment by mourisl** [comment]
Can you show me the 8 lines before and after the read “ST-E00114:418:HHKV7CCXX:8:1109:26484:40020 2:N:0:GCCAAT” in the original file and the command you used?

Thanks.

**Comment by habibr** [comment]
Ups, I made a mistake.

It was not lighter, but another program that I used to remove adapter from the reads that caused the invalid fastq files.

Many apologies...
