### ISSUE TITLE
Lighter 1.1.1 has LIGHTER_VERSION = 1.1.0

### ISSUE THREAD

**Issue by tseemann** [mourisl/Lighter#22]
```
lighter -v
Lighter v1.1.0
```

**Comment by mourisl** [comment]
Thanks! I've fixed it and re-release v1.1.1.

**Comment by tseemann** [comment]
@mourisl - that caused things to break for us, as the SHA256 changed, but I'll patch it back. Thank you.

**Comment by tseemann** [comment]
Thank you
