### ISSUE TITLE
Trimmed and untrimmed read reported

### ISSUE THREAD

**Issue by standage** [mourisl/Lighter#26]
Hi, I ran the following command on several human samples.

```
lighter -r proband_1.fastq -r proband_2.fastq -K 25 3100000000 -t 8
```

Note that I did not invoke the `--trim` flag. However, the output contains many many reads that are reported twice in Lighter's output. It appears that the first appearance is the trimmed version and the second is the untrimmed version.

```
@E00170:22:H00WVALXX:1:1212:18711:26308/1 cor bad_suffix=9 ak
TCAGATGCTCACCTGGGGGTGTGGGTGCTGCTCCAGGTTGTCAGATGCTCACCAGGGGGTGCAGGGGCTGCTCCC  
--
@E00170:22:H00WVALXX:1:1212:18711:26308/1 cor bad_suffix=9 ak                                                                                               
TGCTCGCCTTGGGGTGTGGGTGCTCTTCCAGGCTGTCACGTGCGCACCTGGGGGTGCAGGGTGCTGTTGCAGGCTGTCAGATGCTCACCTGGGGGTGTGGGTGCTGCTCCAGGTTGTCAGATGCTCACCAGGGGGTGCAGGGGCTGCTCCC
--
@E00170:22:H00WVALXX:1:2114:24984:53135/1
TCCATTCCAGTTGATTCCATTCCACTCCGTTTCATTCCATT
--
@E00170:22:H00WVALXX:1:2114:24984:53135/1
TTCCACTCCATTCCATATTATTCCATTACACTCCATTCCATTCTATTACTTTCATTTCCATTCAATTCCATTCCAGTTGATTCCATTCCACTCCGTTTCATTCCATTTGAGTCCATTCCATTCCATTCCATTCCATTCCGTTCCATTCCAT
```

The duplicated reads aren't adjacent in the output, sometimes there is error correction metadata appended to the record and sometimes there is not. Any idea what the problem might be?

This was run using the latest master (a768570ef8a4e726f65114c8e29f517e4deb0b81) on Linux.

**Comment by mourisl** [comment]
This is quite weird. Even if Lighter tries to trim, it will only remove the last bases not the first bases. Do you still have the summary text reported by Lighter? And are you sure the original read files do not contain both versions? Thanks.

Li

**Comment by standage** [comment]
I just did some more detective work, and figured out that the problem was with the input. I got my reads in BAM format, and had to convert back to Fastq for error correction. The bam-to-fastq converter I used reported supplementary/secondary hard-clipped alignments, thus the duplicated records.

Thanks for your quick response!
