### ISSUE TITLE
Appropriate for 2.5 Gbp Plant Genome?

### ISSUE THREAD

**Issue by AllisonStander** [mourisl/Lighter#28]
I am assembling a highly heterozygous, repetitive, 2.5 Gbp plant genome (rooibos). My dataset is around 320 GB (zipped) (Illumina paired-end, and mate-pair data).

Due to time constraints, I would like to know if Light be suitable for my dataset and biological system, before having the tool installed and running my dataset on it? 

Thanks for your time.

Kind regards,
Allison

**Comment by mourisl** [comment]
Lighter should work for such data. For the parameters, if this is very heterozygous, you can regard this as a 5Gb plant genome (2.5*ploidy).

**Comment by AllisonStander** [comment]
Thank you for the quick response and advice!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
