### ISSUE TITLE
Multiple input files

### ISSUE THREAD

**Issue by AllisonStander** [mourisl/Lighter#29]
Good day,

I have 16 .gz files (8 forward, 8 reverse). Can I write the command as follows:

`./lighter -r one1.fq.gz -r one2.fq.gz -r two1.fq.gz -r two2.fq.gz -r three1.gz -r three2.gz -k 17 5000000 0.1 -t 32`

With all 16 input files in the same command?

Kind regards,
Allison

**Comment by mourisl** [comment]
Yes. Lighter supports reading 100 files. 
You need to change the parameters for -k to match the k-mer size, genome size and sequencing depth you use though.

**Comment by AllisonStander** [comment]
I had a successful run with the following parameters:
`-k 31 5000000000 0.07 -t 24 `

I just remembered though, that my data contains non-nuclear DNA as well as nuclear DNA. Meaning that the coverage would be less than calculated.

Do you perhaps have any advice on how I should carry out the analysis, keeping in mind the lower coverage? Or will this not have such a great effect on Lighter?

Kind regards,
Allison

**Comment by mourisl** [comment]
I don't think it will have a big effect if the coverage number is off by a bit. From my experience, the performance is about the same even the coverage is off by 10%. Is this your case?

**Comment by AllisonStander** [comment]
Thank you.

I am not yet sure what percentage of my reads are from non-nuclear origin.
I will need to find out whether there is a way to determine this.

**Comment by mourisl** [comment]
I think there are some tools to infer the genome size from the sequencing data. 

What is the correction summary output from Lighter?

**Comment by AllisonStander** [comment]
Correction summary output from Lighter:

[2018-11-29 06:24:44] =============Start====================
[2018-11-29 06:25:03] Bad quality threshold is "7"
[2018-11-29 10:16:31] Finish sampling kmers
[2018-11-29 10:16:31] Bloom filter A's false positive rate: 0.000710
[2018-11-29 14:08:39] Finish storing trusted kmers
[2018-11-30 05:22:44] Finish error correction
Processed 2436691688 reads:
        1461925922 are error-free
        Corrected 2567931172 bases(2.634408 corrections for reads with errors)
        Trimmed 0 reads with average trimmed bases 0.000000
        Discard 0 reads

**Comment by mourisl** [comment]
I think the numbers look alright.

**Comment by AllisonStander** [comment]
Okay thank you very much. I will also have a look at genome size estimation tools (and read up on contamination, and how it will effect the size estimation).
