### ISSUE TITLE
Segmentation fault when using -t > 2

### ISSUE THREAD

**Issue by ealdraed** [mourisl/Lighter#30]
Hello @mourisl,

I wanted to use Lighter as part of the shovill pipeline (with several threads) but ran into a problem with a "Segmentation fault (core dumped)" error meesage right after the message "Finish storing trusted kmers". I had a look at main.cpp and realized you are handling the processing based on the number of threads differently (1, 2 and more than 2). I tried to pinpoint the problem and finally could resolve it by changing lines [806-809](https://github.com/mourisl/Lighter/blob/df39031f8254f8351852f9f8b51b643475226ea0/main.cpp#L806-L809) to read:

```
int batchSize[3] ;
bool init = true, canJoinOutputThread = false ;
int tag = 2, prevTag ;
int fileInd[3] ;
```
Notice I enlarged the arrays' size to 3, as I think you will use three batches later on.

I realized by trying Linuxbrew, that the provided binary (Bottle) works without problems. If I build the Formula from source (using the system's GCC 7.3.0) I will get the above error. If I install Linuxbrew's GCC version 5.5.0 and compile the Formula from source it will again work like the Bottle.

I have not provided a pull request as I am unsure of the nature of this problem. Is it possible that GCC 5.5.0 might tolerate the wrong array size (if wrong at all) whereas GCC 7.3.0 is stricter with it?

Any comments on this?

Best regards
Stefan

**Comment by mourisl** [comment]
Thanks for pointing this out! This is definitely a bug in the code! Probably this could fix the issues #25 and #27. Thank you!

**Comment by ealdraed** [comment]
Hi, thank you for your quick response.

I noticed you missed the version increase in [line 21](https://github.com/mourisl/Lighter/blob/b8699716a3de43ee6df72b5240827eaa557d2f4c/main.cpp#L21).

**Comment by mourisl** [comment]
Thanks. I've updated it and re-release the code.
