### ISSUE TITLE
line 15:  7429 Segmentation fault

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [mourisl/Lighter#35]
Running a small test data set ona chloroplast genome, approx. 40X coverage. I have 190GB ram so that is not the problem:

lighter -r reads-cp.fastq -t 48 -k 17 300000 0.175 

[2023-07-28 11:58:45] =============Start====================
[2023-07-28 11:58:45] Bad quality threshold is "*"
[2023-07-28 11:58:46] Finish sampling kmers
[2023-07-28 11:58:46] Bloom filter A's false positive rate: 0.001099
[2023-07-28 11:58:46] Finish storing trusted kmers
/local/spool/pbs/mom_priv/jobs/91431209.gadi-pbs.SC: line 15:  7429 Segmentation fault      lighter -r /g/data/dy44/r12.1_doryanthes/reads-cp.fastq -t 48 -k 17 300000 0.175

**Comment by theo-allnutt-bioinformatics** [comment]
This is happening with any setting of -t.

**Comment by mourisl** [comment]
Could you please show me the first a few lines of the fastq file? What version of LIghter did you use?

**Comment by theo-allnutt-bioinformatics** [comment]
Latest version.

fastq:
@a19dd80e-0db8-48a9-8374-69cf9b405437_166
GAAGTAAATACTAAACTTCCCTCGACTCCATGTCCGAATAAAATAAAGTGGTAATAAGTTCTAAAGAATCAATTGATTCATGGTTGAAATCCCTCCATGATGTGATGCATTTAAAATTTTGACTAAGCGAGGGATCAAATGGTATAGTTCCTTTGTTGGTAGCTTGGAGGATTACAAACATGACTATTGCTTTCCAATTAGCTGTTTTTGCATTAATTGTGACTTCATCAATCTTACTTATTAGTGTACCCGTTGTATTTGCTTCTTCTGATGGTTGGTCAAGTAACAAAAATGTTGTATTTTCCGGTACATCATTATGGATTGGATTAGTCTTTCTGGTAGCTATCCTTAATTCTCTCATCTCTTGAACTTCTTTGGTATTTCCCC

n.b. the reads are ONT so very long.

**Comment by theo-allnutt-bioinformatics** [comment]
reads:

https://drive.google.com/file/d/15IMUm_N3w4sImK46_zOL6_pKF0GI4SVY/view?usp=drive_link

**Comment by mourisl** [comment]
Thank you for sharing the data. Lighter is for a short read corrector, and has a minimal ability to correct indel errors which are common in long reads. Lighter also assumes a max read length of 1024, which may cause this crash. Therefore, I would suggest using other methods for long-read error correction.
